Make sure all the existing code follows the coding style
opensuspect/opensuspect pull request #29
Opened 2021-12-23 09:08 UTC by TheSecondReal0

2021-12-23 09:27 UTC, nicemicro commented
could you please check if all these guidelines are in the coding style guide md file and add them there if not?
maybe we should also give some numbers to each point in the style guide for easier reference

2021-12-25 10:54 UTC, moxvallix requested changes
i think this file should be renamed either to STYLEGUIDE.md, CODE_STYLE.md, or code_styleguide.md to meet our naming schemes. The all caps file name convention seems to be for the more meta files in base, so maybe STYLEGUIDE is a fit?

2021-12-25 10:54 UTC, moxvallix commented on code-styleguide.md
>      func computeTime(daysElapsed):
should this be computerTime to match the bad example above?

2021-12-25 10:54 UTC, moxvallix commented on code-styleguide.md
> +Look at how others named things in the code, and foolow that.
follow, not foolow

2021-12-26 08:37 UTC, nicemicro approved these changes
I like it.

2021-12-26 08:57 UTC, moxvallix approved these changes
looks good

2021-12-26 09:04 UTC, merged